version: "3.9"

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./config:/config
      - .//data
      - ./sites:/srv
    networks:
      - caddy_net
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --schedule "0 4 * * *" --label-enable
    environment:
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      # To notify via webhooks or Slack: https://containrrr.dev/watchtower/usage-notifications/
      # - WATCHTOWER_NOTIFICATION_URL=YOUR_WEBHOOK_URL

networks:
  caddy_net:
    driver: bridge
